# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ESR Application workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["10.x", "12.x"]
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/packages-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-modules-
            ${{ runner.os }}-
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
        with:
          args: deploy --dir=build --prod
